# Generated by Django 4.2.4 on 2023-08-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('category', models.JSONField()),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('num_of_reviews', models.IntegerField()),
            ],
        ),
    ]
