# Generated by Django 4.2.4 on 2023-08-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
